import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./component/header/Header";
import HeaderNotice from "./component/header/HeaderNotice";
import Footer from "./component/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>TrueAstro</title>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}